Repository KiCad/kicad-library-utils, pull requests merged in 2018-03, with the labels that each got.

#218 Add a primitive check for stencil pads
  pcb/rules/F6_3.py
Labels: enhancement

#219 Don't accept STEP files
  pcb/rules/F9_3.py
Labels: bug

#210 New connector symbols and cleanup of generator
  schlib/autogen/KiCadSymbolGenerator/DrawingElements.py
  schlib/autogen/KiCadSymbolGenerator/Point.py
  schlib/autogen/connector/Connector_generator.py
  schlib/autogen/demo-KiCadSymbolGenerator.py
Labels: enhancement, question
